"""empty message

Revision ID: cb8e7828f2be
Revises: 
Create Date: 2020-01-28 01:05:41.975496

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cb8e7828f2be'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('candidate')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidate',
    sa.Column('phone', mysql.TEXT(), nullable=False),
    sa.Column('email', mysql.TEXT(), nullable=False),
    sa.Column('linkedin', mysql.TEXT(), nullable=False),
    sa.Column('exp_years', mysql.TEXT(), nullable=False),
    sa.Column('duration', mysql.TEXT(), nullable=False),
    sa.Column('summary', mysql.TEXT(), nullable=False),
    sa.Column('skills', mysql.TEXT(), nullable=False),
    sa.Column('experience', mysql.TEXT(), nullable=False),
    sa.Column('education', mysql.TEXT(), nullable=False),
    sa.Column('extra', mysql.TEXT(), nullable=False),
    sa.Column('awards', mysql.TEXT(), nullable=False),
    sa.Column('resume', mysql.VARCHAR(length=500), nullable=False),
    sa.Column('filename', mysql.TEXT(), nullable=False),
    sa.Column('complete_resume', mysql.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('resume'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
